/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminStatsRouteImport } from './routes/_authenticated/admin.stats'
import { Route as ApiPublicHooksTrackClickRouteImport } from './routes/api/public/hooks/track-click'
import { Route as ApiPublicHooksIngestConcertsRouteImport } from './routes/api/public/hooks/ingest-concerts'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminStatsRoute = AuthenticatedAdminStatsRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksTrackClickRoute =
  ApiPublicHooksTrackClickRouteImport.update({
    id: '/api/public/hooks/track-click',
    path: '/api/public/hooks/track-click',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIngestConcertsRoute =
  ApiPublicHooksIngestConcertsRouteImport.update({
    id: '/api/public/hooks/ingest-concerts',
    path: '/api/public/hooks/ingest-concerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/api/public/hooks/ingest-concerts': typeof ApiPublicHooksIngestConcertsRoute
  '/api/public/hooks/track-click': typeof ApiPublicHooksTrackClickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/api/public/hooks/ingest-concerts': typeof ApiPublicHooksIngestConcertsRoute
  '/api/public/hooks/track-click': typeof ApiPublicHooksTrackClickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/api/public/hooks/ingest-concerts': typeof ApiPublicHooksIngestConcertsRoute
  '/api/public/hooks/track-click': typeof ApiPublicHooksTrackClickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin/stats'
    | '/api/public/hooks/ingest-concerts'
    | '/api/public/hooks/track-click'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin/stats'
    | '/api/public/hooks/ingest-concerts'
    | '/api/public/hooks/track-click'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin/stats'
    | '/api/public/hooks/ingest-concerts'
    | '/api/public/hooks/track-click'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksIngestConcertsRoute: typeof ApiPublicHooksIngestConcertsRoute
  ApiPublicHooksTrackClickRoute: typeof ApiPublicHooksTrackClickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/stats': {
      id: '/_authenticated/admin/stats'
      path: '/admin/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AuthenticatedAdminStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/track-click': {
      id: '/api/public/hooks/track-click'
      path: '/api/public/hooks/track-click'
      fullPath: '/api/public/hooks/track-click'
      preLoaderRoute: typeof ApiPublicHooksTrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-concerts': {
      id: '/api/public/hooks/ingest-concerts'
      path: '/api/public/hooks/ingest-concerts'
      fullPath: '/api/public/hooks/ingest-concerts'
      preLoaderRoute: typeof ApiPublicHooksIngestConcertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminStatsRoute: typeof AuthenticatedAdminStatsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminStatsRoute: AuthenticatedAdminStatsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksIngestConcertsRoute: ApiPublicHooksIngestConcertsRoute,
  ApiPublicHooksTrackClickRoute: ApiPublicHooksTrackClickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
